### ISSUE TITLE
if spike_clusters.npy doesn't exist, fails to load template-gui

### ISSUE THREAD

**Issue by yagui** [cortex-lab/phylib#1]
in phylib/io/model.py, line 414, when spike_clusters.npy doesn't exist it is not created properly because 'path' is not defined.
I'm not sure if is the intended behaviour but adding:
path = self.dir_path + '/spike_clusters.npy'
at line 414 allows template gui to load correctly

**Comment by rossant** [comment]
thanks! fixed
