### ISSUE TITLE
Can not open binary file with esoteric extension ?

### ISSUE THREAD

**Issue by yger** [cortex-lab/phylib#25]
When opening phy with a raw binary file that has the .raw extension, I have the following error

klass, arg, kwargs = _get_ephys_constructor(obj[0], **kwargs)
OSError: [Errno Unknown file extension: %s.] .raw

Can it be bypassed?

**Comment by rossant** [comment]
should be fixed on master

**Comment by yger** [comment]
Indeed, thanks!
