### ISSUE TITLE
_load_ function problems

### ISSUE THREAD

**Issue by adehad** [cortex-lab/phylib#3]
1. Need to `from glob import glob` for `_load_metadata` 
https://github.com/cortex-lab/phylib/blob/f72d0a5f58ba1a741bfa88feba7ee0f64ef721c5/phylib/io/model.py#L321-L324
2. `self.dir_path`  does not seem to be recognised as a Path object in `_load_spike_samples`
https://github.com/cortex-lab/phylib/blob/f72d0a5f58ba1a741bfa88feba7ee0f64ef721c5/phylib/io/model.py#L426-L429
`self.dir_path = Path(dir_path)` didn't work in the constructor for me, so I used this non-ideal work around.
```
path = self.dir_path +'/'+ 'spike_times.npy'
path = Path(path)
```

`phy` GUI opens after this, but then produces an assertion error:
```
c:\conda\miniconda3\envs\phydev\lib\site-packages\numpy\core\_methods.py:75: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims)
c:\conda\miniconda3\envs\phydev\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
c:\conda\miniconda3\envs\phydev\lib\site-packages\phylib\utils\geometry.py:161: RuntimeWarning: invalid value encountered in less
  assert np.all(data_bounds[:, 1] < data_bounds[:, 3])

...
Traceback (most recent call last):
  File "c:\conda\miniconda3\envs\phydev\lib\site-packages\phy\apps\template\gui.py", line 723, in init_cluster_ids
    view.plot()
  File "c:\conda\miniconda3\envs\phydev\lib\site-packages\phy\cluster\views\template.py", line 158, in plot
    self._plot_templates(bunchs, data_bounds=data_bounds)
  File "c:\conda\miniconda3\envs\phydev\lib\site-packages\phy\cluster\views\template.py", line 103, in _plot_templates
    self.visual.add_batch_data(**data, data_bounds=data_bounds)
  File "c:\conda\miniconda3\envs\phydev\lib\site-packages\phy\plot\base.py", line 142, in add_batch_data
    data = self.validate(**kwargs)
  File "c:\conda\miniconda3\envs\phydev\lib\site-packages\phy\plot\visuals.py", line 296, in validate
    data_bounds = _get_data_bounds(data_bounds, length=n_signals)
  File "c:\conda\miniconda3\envs\phydev\lib\site-packages\phylib\utils\geometry.py", line 193, in _get_data_bounds
    _check_data_bounds(data_bounds)
 File "c:\conda\miniconda3\envs\phydev\lib\site-packages\phylib\utils\geometry.py", line 161, in _check_data_bounds
    assert np.all(data_bounds[:, 1] < data_bounds[:, 3])
AssertionError
```

**Comment by rossant** [comment]
> 1. Need to `from glob import glob` for `_load_metadata`

What is your version of Python?

**Comment by adehad** [comment]
Python 3.7.3

**Comment by adehad** [comment]
All except Assertion Error addressed by: ec4cf662b6fed28db206e7c7ba41285e010fdd57

**Comment by rossant** [comment]
for the assertion error could you send me your dataset?

**Comment by adehad** [comment]
Have attached it here, with the data binary:
[kilosort_dataset.zip](https://github.com/cortex-lab/phylib/files/3256410/kilosort_dataset.zip)

**Comment by rossant** [comment]
There are infinite values in `amplitudes.npy`. I'll push a fix to skip these points but the real question is: why does kilosort find infinite values as amplitudes?

**Comment by rossant** [comment]
Same problem for `template_features.npy`.

**Comment by rossant** [comment]
try to remove `C:\SPB_Data\.phy\plugins\phycontrib_loader.py` ?

**Comment by adehad** [comment]
> 
> 
> try to remove `C:\SPB_Data\.phy\plugins\phycontrib_loader.py` ?

Tactical. Can confirm that fixes the issue.
