### ISSUE TITLE
Adding a Refractory Period Violation number somewhere

### ISSUE THREAD

**Issue by yger** [cortex-lab/phylib#6]
How easy is it to add an extra column to the ClusterView? Because I saw you added the firing rates, which is great, but what about Refractory Period Violation? I.e. what are the percentage of spikes (among all the spikes for a given units) such that the interspike interval is below a certain number (2 ms for example). This is something quite useful, to quickly identify MUA (since they have high level of RPV). 
And more generally, are columns hard-coded somewhere, or is there a way to provide custom functions for sorting the cells?

**Comment by rossant** [comment]
See here: https://phy.readthedocs.io/en/latest/plugins/#defining-a-custom-cluster-metrics

**Comment by yger** [comment]
Thanks!
